# Generated by Django 3.2.12 on 2022-03-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_alter_movies_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Cakes',
        ),
    ]
